### ISSUE TITLE
No available version compatible with the installed Atom version: 1.2.1

### ISSUE THREAD

**Issue by qingfeng** [void-main/atom-2048#5]
(*'-') < apm install atom-2048                                                                                                    15-11-18 19:05
Installing atom-2048 to /Users/qingfeng/.atom/packages ✗
No available version compatible with the installed Atom version: 1.2.1

**Comment by tonyzhu** [comment]
@qingfeng 清风老师好

**Comment by void-main** [comment]
@qingfeng 清风老师好～

**Comment by qingfeng** [comment]
原来都是自己人。。。

**Comment by void-main** [comment]
@qingfeng 哈哈～今晚抽空更新下。。。

**Comment by void-main** [comment]
@qingfeng https://github.com/void-main/atom-2048/releases/tag/v3.0.0

搞定了～

**Comment by qingfeng** [comment]
赞！我安一个去

**Comment by void-main** [comment]
然而还有bug。。。新版的api对keydown event用preventDefault好像没用了。。等有空再看看吧～
